---
sudo: required
language: python
services: docker

env:
  - version=">=2.4,<2.5" distro="alpine-latest"
  - version=">=2.5,<2.6" distro="alpine-latest"
  - version=">=2.6,<2.7" distro="alpine-latest"
  - version=">=2.4,<2.5" distro="alpine-edge"
  - version=">=2.5,<2.6" distro="alpine-edge"
  - version=">=2.6,<2.7" distro="alpine-edge"
  - version=">=2.4,<2.5" distro="archlinux"
  - version=">=2.5,<2.6" distro="archlinux"
  - version=">=2.6,<2.7" distro="archlinux"
  - version=">=2.4,<2.5" distro="centos-6"
  - version=">=2.5,<2.6" distro="centos-6"
  - version=">=2.6,<2.7" distro="centos-6"
  - version=">=2.4,<2.5" distro="centos-latest"
  - version=">=2.5,<2.6" distro="centos-latest"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version=">=2.4,<2.5" distro="debian-latest"
  - version=">=2.5,<2.6" distro="debian-latest"
  - version=">=2.6,<2.7" distro="debian-latest"
  - version=">=2.4,<2.5" distro="debian-stable"
  - version=">=2.5,<2.6" distro="debian-stable"
  - version=">=2.6,<2.7" distro="debian-stable"
  - version=">=2.4,<2.5" distro="debian-unstable"
  - version=">=2.5,<2.6" distro="debian-unstable"
  - version=">=2.6,<2.7" distro="debian-unstable"
  - version=">=2.4,<2.5" distro="fedora-latest"
  - version=">=2.5,<2.6" distro="fedora-latest"
  - version=">=2.6,<2.7" distro="fedora-latest"
  - version=">=2.4,<2.5" distro="fedora-rawhide"
  - version=">=2.5,<2.6" distro="fedora-rawhide"
  - version=">=2.6,<2.7" distro="fedora-rawhide"
  - version=">=2.4,<2.5" distro="opensuse-leap"
  - version=">=2.5,<2.6" distro="opensuse-leap"
  - version=">=2.6,<2.7" distro="opensuse-leap"
  - version=">=2.4,<2.5" distro="opensuse-tumbleweed"
  - version=">=2.5,<2.6" distro="opensuse-tumbleweed"
  - version=">=2.6,<2.7" distro="opensuse-tumbleweed"
  - version=">=2.4,<2.5" distro="ubuntu-artful"
  - version=">=2.5,<2.6" distro="ubuntu-artful"
  - version=">=2.6,<2.7" distro="ubuntu-artful"
  - version=">=2.4,<2.5" distro="ubuntu-latest"
  - version=">=2.5,<2.6" distro="ubuntu-latest"
  - version=">=2.6,<2.7" distro="ubuntu-latest"
  - version=">=2.4,<2.5" distro="ubuntu-devel"
  - version=">=2.5,<2.6" distro="ubuntu-devel"
  - version=">=2.6,<2.7" distro="ubuntu-devel"

matrix:
  allow_failures:
    - env: version=">=2.4,<2.5" distro="alpine-edge"
    - env: version=">=2.5,<2.6" distro="alpine-edge"
    - env: version=">=2.6,<2.7" distro="alpine-edge"
    - env: version=">=2.4,<2.5" distro="debian-unstable"
    - env: version=">=2.5,<2.6" distro="debian-unstable"
    - env: version=">=2.6,<2.7" distro="debian-unstable"
    - env: version=">=2.4,<2.5" distro="fedora-rawhide"
    - env: version=">=2.5,<2.6" distro="fedora-rawhide"
    - env: version=">=2.6,<2.7" distro="fedora-rawhide"
    - env: version=">=2.4,<2.5" distro="ubuntu-devel"
    - env: version=">=2.5,<2.6" distro="ubuntu-devel"
    - env: version=">=2.6,<2.7" distro="ubuntu-devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install ansible"${version}"
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "kxotmvIc5AXsw6cMR5UDP4a0s6NOkLEdf+pBohzTcwAEleqsIG1wNwv6vHtw1VMUkD8lAKv5UTGS8ail5jFb5/oIXjUV6DbHlkcqn9n4HAf/Xxvc4/XkPfSu1LQLX1F/pfMt21+mBfo8Yjbnl1oa40Nr6I6/VxpAslUmTubJD4cupz28svdNUS4M3vNA14+r9CNpjfsU6uxNV3ewvbrW8JUd94qvL82wFPQ1nhht0bZbhinO/tjir+WfkI7FPDOCl1xkW5fdWB4QIQe6uJ5MiFJPCsR3eHhH6AHl23f6the3a75Sj7PPXokPyioqjdK6eNX0bfj3qOLWhn7LDf3AVb1vQ7qo00b+CYsrs19xULsF1JuF0NPWH9JnLzl0UXKFweQEN8YiVGREhNUCN8RQcsAQODsJcUwP2WBN7yFV1pYGoNhsg7c299i6TG31r55MHD8SJ/XavFEdD3quZ42zK4B7t3GylTkds+l+crmqQ0z/AbPVxUOHUJC3ylkKBYpv1W5WdR90r08mNWCgxQPPb77Wxdud7n6TADmcMJG8vZj9MMMv8/FspC1RFN623AJGe3OVYUkt3P8pFt5LKS0SOhY5hdX2/xRbVAr+Qy7PRdXJJv8+M/r1dqgGIURAN3PqJj/aUw+kY514TXgUHCFAz/+SsNNY4Pf58kj0Ww9k2wA="
  email: false
