---
# tasks file for artifactory
- name: install requirements
  package:
    name: "{{ artifactory_requirements }}"
    state: "{{ artifactory_package_state }}"
  register: artifactory_install_requirements
  until: artifactory_install_requirements is succeeded
  retries: 3

- name: create group for artifactory
  group:
    name: "{{ artifactory_group }}"
    state: present

- name: create user for artifactory
  user:
    name: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    system: yes

- name: ensure artifactory_download_directory exists
  file:
    path: "{{ artifactory_download_directory }}"
    state: directory

- name: download artifactory
  unarchive:
    src: "{{ artifactory_zip }}"
    dest: "{{ artifactory_download_directory }}"
    remote_src: yes
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    creates: "{{ artifactory_home }}"
  register: downloadartifactory
  until: downloadartifactory is succeeded
  retries: 3

- name: create artifactory service
  import_role:
    name: robertdebock.service

- name: start and enable artifactory
  service:
    name: artifactory
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker" or artifactory_ignore_docker
