---
# tasks file for artifactory

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install yum repository
  ansible.builtin.get_url:
    url: "https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo"
    dest: /etc/yum.repos.d/bintray-jfrog-artifactory-rpms.repo
    mode: "0640"
  when:
    - ansible_pkg_mgr in [ "dnf", "yum", "dnf5" ]

- name: Configure apt repository
  when:
    - ansible_pkg_mgr in [ "apt" ]
  block:
    - name: Trust gpg key
      ansible.builtin.apt_key:
        url: "https://releases.jfrog.io/artifactory/api/gpg/key/public"
        state: present
        validate_certs: false

    - name: Install deb repository
      ansible.builtin.apt_repository:
        repo: "deb https://releases.jfrog.io/artifactory/artifactory-debs {{ ansible_distribution_release | lower }} main"
        state: present

- name: Install package
  ansible.builtin.package:
    name: "{{ artifactory_package }}"
    state: present

- name: Ensure artifactory_file_store_dir exists
  ansible.builtin.file:
    path: "{{ artifactory_file_store_dir }}"
    state: directory
    mode: "0755"
    owner: artifactory
    group: artifactory

- name: Ensure artifactory home directory exists
  ansible.builtin.file:
    path: "{{ artifactory_home }}"
    state: directory
    mode: "0755"
    owner: artifactory
    group: artifactory

- name: Configure artifactory
  ansible.builtin.template:
    src: binarystore.xml.j2
    dest: "{{ artifactory_home }}/binarystore.xml"
    mode: "0644"
    owner: artifactory
    group: artifactory
  notify:
    - Restart artifactory

- name: Set ownership for artifactory_logs
  ansible.builtin.file:
    path: "{{ artifactory_logs }}"
    state: directory
    mode: "0755"
    owner: artifactory
    group: artifactory

- name: Install systemd service file
  ansible.builtin.copy:
    src: /opt/jfrog/artifactory/misc/service/artifactory.service
    dest: /usr/lib/systemd/system/artifactory.service
    mode: "0644"
    owner: root
    group: root
    remote_src: true
  when:
    - ansible_service_mgr == "systemd"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Start and enable artifactory
  ansible.builtin.service:
    name: artifactory
    state: started
    enabled: true
