---
# tasks file for artifactory
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install yum repository
  get_url:
    url: "https://bintray.com/jfrog/artifactory-rpms/rpm"
    dest: /etc/yum.repos.d/bintray-jfrog-artifactory-oss-rpms.repo
  when:
    - ansible_pkg_mgr in [ "dnf", "yum" ]

- name: configure apt repository
  block:
    - name: trust gpg key
      apt_key:
        url: "https://api.bintray.com/orgs/jfrog/keys/gpg/public.key"
        state: present
        validate_certs: no

    - name: install deb repository
      apt_repository:
        repo: "deb https://jfrog.bintray.com/artifactory-debs {{ ansible_distribution_release | lower }} main"
        state: present
  when:
    - ansible_pkg_mgr in [ "apt" ]

- name: install package
  package:
    name: jfrog-artifactory-oss
    state: present

- name: ensure artifactory_file_store_dir exists
  file:
    path: "{{ artifactory_file_store_dir }}"
    state: directory
    mode: "0755"

- name: configure artifactory
  template:
    src: binarystore.xml.j2
    dest: "{{ artifactory_home }}/binarystore.xml"
    mode: "0644"
  notify:
    - restart artifactory

- name: start and enable artifactory
  service:
    name: artifactory
    state: started
    enabled: yes
