---
# tasks file for artifactory
- name: install requirements
  package:
    name: "{{ artifactory_requirements }}"
    state: present
  register: artifactory_install_requirements
  until: artifactory_install_requirements is succeeded
  retries: 3

- name: create group for artifactory
  group:
    name: "{{ artifactory_group }}"
    state: present

- name: create user for artifactory
  user:
    name: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    system: yes

- name: ensure artifactory_download_directory exists
  file:
    path: "{{ artifactory_download_directory }}"
    state: directory

- name: download artifactory
  unarchive:
    src: "{{ artifactory_zip }}"
    dest: "{{ artifactory_download_directory }}"
    remote_src: yes
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    creates: "{{ artifactory_home }}"
  register: downloadartifactory
  until: downloadartifactory is succeeded
  retries: 3

- name: set password for artifactory for version below 6.8.0
  template:
    src: bootstrap.creds.j2
    dest: "{{ artifactory_download_directory }}/artifactory-oss-{{ artifactory_version }}/etc/bootstrap.creds"
    mode: 0600
  notify:
    - restart artifactory
  when:
    - artifactory_version is version('6.8.0', '<')

- name: set password for artifactory for version 6.8.0 and above
  uri:
    url: "https://localhost:8081/access/api/v1/users/admin"
    user: access-admin
    password: password
    method: PATCH
    body:
      password: "{{ artifactory_password }}"
    status_code: 201
    body_format: json
  when:
    - artifactory_version is version('6.8.0', '>=')

- name: create artifactory service
  import_role:
    name: robertdebock.service

- name: start and enable artifactory
  service:
    name: artifactory
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
