---
# tasks file for artifactory
- name: include assert.yml
  include_tasks: assert.yml

- name: install requirements
  package:
    name: "{{ artifactory_requirements }}"
    state: present

- name: create group for artifactory
  group:
    name: "{{ artifactory_group }}"
    state: present

- name: create user for artifactory
  user:
    name: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    system: yes

- name: ensure artifactory_download_directory exists
  file:
    path: "{{ artifactory_download_directory }}"
    state: directory
    mode: "0755"

- name: download artifactory
  unarchive:
    src: "{{ artifactory_zip }}"
    dest: "{{ artifactory_download_directory }}"
    remote_src: yes
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    creates: "{{ artifactory_home }}"
    mode: "0755"
  notify:
    - restart artifactory

- name: ensure artifactory_file_store_dir exists
  file:
    path: "{{ artifactory_file_store_dir }}"
    state: directory
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: "0755"

- name: configure artifactory
  template:
    src: binarystore.xml.j2
    dest: "{{ artifactory_home }}/etc/binarystore.xml"
    mode: "0644"
  notify:
    - restart artifactory

- name: create artifactory service
  import_role:
    name: robertdebock.service

- name: start and enable artifactory
  service:
    name: artifactory
    state: started
    enabled: yes
