---
# tasks file for core_dependencies

- name: install packages
  package:
    name: "{{ core_dependencies }}"
    state: present
  notify:
    - gather facts

- name: try to install pip packages
  pip:
    name: "{{ core_dependencies_pip_packages }}"
    state: present
  failed_when: no
  notify:
    - gather facts

- name: flush handlers
  meta: flush_handlers
